postgresql: &postgresql
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV['JUVO_DB_USER'] %>
  password: <%= ENV['JUVO_DB_PASSWORD'] %>
  database: rails10

development:
  <<: *postgresql
  database: rails10_development